### PR TITLE
ATM-39: Add Base Theme to Meetup Repo

### PR DESCRIPTION
**Pull request by ninjaofawesome**
# Description

- This PR adds a base theme to the repository.  It currently only has font families and colors. 

## Issue
[#39](https://github.com/astoria-tech/meetup/issues/39)

## Notes
- This PR does not include a dark theme as currently it is not in use.  However, it would be nice to have a dark theme at some point, this could be ticketed separately.
- The "gradients" mentioned in the issue were meaning like a gradient background on an element, but there are different tints of the `primary`, `secondary`, and `tertiary` colors named `primaryGradient`, `secondaryGradient`, and `tertiaryGradient`.  These can be renamed for clarity if desired.
- This PR uses locally hosted font files, could be somewhere on a CDN.  This could be a fast follow ticket if we prefer to go that direction.  (Also unfortunately did not use system fonts against my own suggestion.)
- The colors and font families were arbitrarily chosen from one of the existing flyers.  If we'd like a different set of colors or fonts, happy to switch things up!
- Unsure if the `postCSS` package is needed for imports, but added it so that directives could be imported and used as needed, where needed.   Could the reference to the `postCss` package  be in the `tailwind.config.mjs` file under plugins?
- Added `autoprefixer` for vendor prefixes.  If it feels unnecessary, for now I can remove it.
- Organized files for directives and theming into a new `src/styles` directory.
- Only minimally applied styles to elements in the feed, as that would be out of scope at the moment.

## How to test
- Pull this branch and fire it up with `npm run dev`
- See that the base font family is now `NotoSans`
- Add a color to any element from the themes, see it apply appropriately.

## Screenshots
Swatches:
Screen Shot 2024-04-24 at 1 53 03 AM
Font Families:
Screen Shot 2024-04-25 at 12 25 48 AM
Example of type elements applied on feed:
Screen Shot 2024-04-25 at 12 57 14 AM

### CODE REVIEW

**Review by reggi — APPROVED** [review]
🎉  Looks great! I normally wouldn't commit on your branch but I had to add merge conflicts from main & add some configuration for astro to point to the right files. Also ran into snag with `Bold` in one of the file names and had some issues getting CI to pass. 

I'm curious how the images of swatches / fonts are being made, and if you could add them as an html page on the site?

**Comment by reggi** [comment]
I'm curious how you generated those swatch / font demo images, could you add just be html on the site `/design` page? No worries if not.

**Comment by reggi** [comment]
@ninjaofawesome let me know if this is ready to be merged 👍

**Comment by reggi** [comment]
@ninjaofawesome let me know if this is ready to be merged 👍

**Comment by ninjaofawesome** [comment]
> I'm curious how the images of swatches / fonts are being made, and if you could add them as an html page on the site?

I actually did it the most hack-tastic way possible by just adding each swatch manually (and then removing it before putting out the PR).  How about I make a separate issue for that and get on that next?

**Pull request merged**
